# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'style.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(402, 464)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setHorizontalSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(250, 250, 250);\n"
"border: 1px solid;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gerarRelatorio = QtWidgets.QPushButton(self.frame)
        self.gerarRelatorio.setGeometry(QtCore.QRect(10, 380, 381, 31))
        self.gerarRelatorio.setStyleSheet("font: 75 11pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(20, 20, 20);\n"
"color: rgb(255, 255, 255);")
        self.gerarRelatorio.setObjectName("gerarRelatorio")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setEnabled(False)
        self.progressBar.setGeometry(QtCore.QRect(10, 420, 301, 31))
        self.progressBar.setMouseTracking(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.texto = QtWidgets.QPlainTextEdit(self.frame)
        self.texto.setGeometry(QtCore.QRect(10, 130, 381, 81))
        self.texto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.texto.setObjectName("texto")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 220, 121, 151))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 101, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.dataInicio = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dataInicio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dataInicio.setObjectName("dataInicio")
        self.verticalLayout.addWidget(self.dataInicio)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.dataFim = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dataFim.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dataFim.setObjectName("dataFim")
        self.verticalLayout.addWidget(self.dataFim)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(40, 10, 41, 20))
        self.label_5.setStyleSheet("border: 0px;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 361, 41))
        self.label_6.setStyleSheet("font: 25 20pt \"Microsoft JhengHei UI Light\";\n"
"border: 0px;")
        self.label_6.setObjectName("label_6")
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame)
        self.lcdNumber.setGeometry(QtCore.QRect(320, 420, 71, 31))
        self.lcdNumber.setObjectName("lcdNumber")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_2.setGeometry(QtCore.QRect(140, 250, 133, 16))
        self.checkBox_2.setStyleSheet("border: 0px;")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_1 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_1.setGeometry(QtCore.QRect(140, 230, 164, 16))
        self.checkBox_1.setStyleSheet("border: 0px;")
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_6.setGeometry(QtCore.QRect(140, 310, 205, 16))
        self.checkBox_6.setStyleSheet("border: 0px;")
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_4.setGeometry(QtCore.QRect(140, 290, 157, 16))
        self.checkBox_4.setStyleSheet("border: 0px;")
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_7.setGeometry(QtCore.QRect(140, 330, 176, 16))
        self.checkBox_7.setStyleSheet("border: 0px;")
        self.checkBox_7.setObjectName("checkBox_7")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 371, 20))
        self.label_3.setStyleSheet("border: 0px;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 80, 331, 20))
        self.label_4.setStyleSheet("border: 0px;")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(20, 100, 351, 16))
        self.label_7.setStyleSheet("border: 0px;")
        self.label_7.setObjectName("label_7")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_3.setGeometry(QtCore.QRect(140, 270, 161, 17))
        self.checkBox_3.setStyleSheet("border: 0px;")
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Analisador de ativos"))
        self.gerarRelatorio.setText(_translate("MainWindow", "Gerar relatório"))
        self.label.setText(_translate("MainWindow", "Início"))
        self.label_2.setText(_translate("MainWindow", "Fim"))
        self.label_5.setText(_translate("MainWindow", "Período"))
        self.label_6.setText(_translate("MainWindow", "Análise de ativos financeiros"))
        self.checkBox_2.setText(_translate("MainWindow", "Exibir gráfico dos ativos"))
        self.checkBox_1.setText(_translate("MainWindow", "Imprimir tabela com os valores"))
        self.checkBox_6.setText(_translate("MainWindow", "Exibir gráfico de retorno e volatividade"))
        self.checkBox_4.setText(_translate("MainWindow", "Exibir gráfico de volatividade"))
        self.checkBox_7.setText(_translate("MainWindow", "Exibir tabela dos melhores ativos"))
        self.label_3.setText(_translate("MainWindow", "Digite o tiker dos ativos ex:     ;GOLL4.SA; PETR4.SA; GGBR4.SA;"))
        self.label_4.setText(_translate("MainWindow", "Não se esqueça de iniciar e terminar com o sinal de ponto e vírgula"))
        self.label_7.setText(_translate("MainWindow", "Além de separar os tikers com ponto e vírgula"))
        self.checkBox_3.setText(_translate("MainWindow", "Exibir dados normalizados"))


